### ISSUE TITLE
"The package has no main.js file"

### ISSUE THREAD

**Issue by PnfrlEnm** [benfoster04/brackets-drpc#1]
When I try to install it into Brackets, it says "The package has no main.js file", making this unusable. 
:(

**Comment by benfoster04** [comment]
I'm aware of this, as I haven't gotten round to actually developing it. I'll try and release some code this weekend that'll patch the errors for the time being. I'll update the issue if I get around to it.

**Comment by benfoster04** [comment]
Ok, I've updated the package.json file and also added the appropriate meta and dependencies to it. The main infrastructure in main.js has been made too.
