### ISSUE TITLE
Rich Presence Appears to be Broken

### ISSUE THREAD

**Issue by viveksh1** [benfoster04/brackets-drpc#2]
The rich presence appears to be broken, I constantly try to get it to work, but fail every time. I have tried to reconnect to Discord and have even reloaded Brackets and Discord to no success.

**Comment by benfoster04** [comment]
Hi,

I'm well aware that the extension is non-functional for the rich presence aspect. The extension is still in development and is not ready for beta release at this time.

In future, please check the readme.md on the repository and look at code for any signs of missing / present functionality before opening an issue.

Many thanks.

**Comment by viveksh1** [comment]
Alright, but you didn't say it was broken in the readme.md?

**Comment by viveksh1** [comment]
May I ask why did you make this repository if you don't know how to to make Brackets plugins or a Discord Rich Presence?

**Comment by thecrankytech** [comment]
> May I ask why did you make this repository if you don't know how to to make Brackets plugins or a Discord Rich Presence?

Chances are he made it store a project he's learning and working on overtime, as most developers do. GitHub isn't just for releasing projects and plugins, it's also used as storage for projects people are working on hence the reason he's placed a note in the readme specifically stating that the project is still under development and that any help would be appreciated.

**Comment by viveksh1** [comment]
Alright, but he should have said that it's broken somewhere.

**Comment by benfoster04** [comment]
Can't be broken if it wasn't created fully in the first place :/

**Comment by benfoster04** [comment]
And to be honest, you would've thought I'd create a tag/release or publish drpc on the Brackets Extension repository if it was ready for any form of use or beta testing, not to mention I'd probably edit the readme accordingly on where I am with the extension or create one of those fancy Trello rip-off project boards in GitHub for everyone to look at. Sorry if I sound like I'm being an arse mate, just a little hacked off and caught me on a bad day. I saw you send us a friend request on Discord too, send us another if you want to help us out. Same goes for @therealknight if you want to lend a hand; I'd love to get this off the ground.

**Comment by viveksh1** [comment]
I'm looking forward to helping you in any way I can.
