### ISSUE TITLE
Hey can someone tell how to Install this package into brackets

### ISSUE THREAD

**Issue by thrace19** [benfoster04/brackets-drpc#4]

**Comment by gloxiniia** [comment]
Open the Brackets extensions page
After that, click on "install from URL ..."
![image](https://user-images.githubusercontent.com/74350424/99136097-eabcda00-2601-11eb-81c9-2858ca7ecb3a.png)
Put the project URL and click Install
![image](https://user-images.githubusercontent.com/74350424/99136135-14760100-2602-11eb-94b9-80d889fa024c.png)

**Comment by mtripg6666tdr** [comment]
As written in README,  an extension of this repo does not run and any rpc does not appear now. Code is written incompletely.
